### ISSUE TITLE
[feature request] Preserve parents when sorting

### ISSUE THREAD

**Issue by josephdong1000** [Vinzent03/obsidian-sort-and-permute-lines#16]
It would be nice if, in a list, children bullet points were not separated from their parent bullet point.

For example, currently the list:
```
- qux
- cccc
	- aaaa
	- zzze
	- baba
- bbb
	- vvv
- foo
```

sorts alphabetically into:
```
	- aaaa
	- baba
- bbb
- cccc
- foo
- qux
	- vvv
	- zzze
```
But if child-parent bullet point relationships are preserved, the list would be instead sorted to
```
- bbb
	- vvv
- cccc
	- aaaa
	- baba
	- zzze
- foo
- qux
```
This may be more difficult to implement, but I would greatly appreciate such a feature since most of the time when I'm using the plugin to sort my to-do list the architecture of my list becomes broken. Thanks!

**Comment by Vinzent03** [comment]
That's someway similar to #14. I may be able to reuse something from that implementation.

**Comment by vishae** [comment]
I would definitely love this feature too -- currently sorting alphabetically with checkboxes breaks the child-parent relationship

**Comment by cometaro21** [comment]
Thanks for the great sorting plugin.
I too would like this feature.
Currently I sort using the Scoped Sort extension in the VSCode editor, but it would be great to be able to sort using Obsidian alone.

**Comment by Vinzent03** [comment]
I finally got the time :tada:. You can sort the current list (where your cursor is) via the commands `Sort current list recursively`

**Comment by cometaro21** [comment]
I tried it and it worked perfectly.
Thank you so much!

**Comment by Elaws** [comment]
@cometaro21, @Vinzent03 : I can't figure out how to make this work, nothing happens when I use `Sort current list recursively`. I tried with selecting the whole list or just placing the cursor at the top element : nothing happens. 

![image](https://user-images.githubusercontent.com/52013479/204158575-e75811cc-2526-4774-bcbd-02928118a2a5.png)

**Comment by Elaws** [comment]
Mmm... the problem seems to happen as soon as you have multiple lists in a note...

![image](https://user-images.githubusercontent.com/52013479/204158887-7e8f3d91-6c07-4389-8f24-8ef496743fc8.png)

**Comment by Vinzent03** [comment]
@Elaws This is a (I just learned that as well) [loose list](https://spec.commonmark.org/0.26/#loose). They are handled as one list, thus I can't sort them individually. You have to somehow separate them. Or do you want them to be sorted as one list? I don't know then where to exactly put the empty list.

**Comment by Elaws** [comment]
@Vinzent03 : The problem is not that is sorts both lists, the problem is that is sorts none of them : nothing happens.

When you have multiple lists in a note, `sort current list recursively` does not sort anything.

In addition to that, in my example, I would like to be able to sort only the first list (either by selecting it or by having my cursor on it) : 

![image](https://user-images.githubusercontent.com/52013479/204159553-d34e8d17-ccbe-4d7f-8285-ee7c4c3cdf5e.png)

**Comment by josephdong1000** [comment]
Just tried the new feature, at least for single lists it works exactly as intended!

**Comment by Elaws** [comment]
@josephdong1000 : yeah, but not as soon as you have 2 lists on a note, which in my usecase happens much more often than not, it does not work.

**Comment by Vinzent03** [comment]
@Elaws That is not correct. It only doesn't work if you have two lists separated by empty lines, because they are treated as one list in markdown spec. As soon as you put text in between, it should work.
I'm still thinking on how or not I want to solve that.
